name: Mirror to Gitlab Repo

on: [ push ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_DEPLOY_KEY }}
        with:
          source-repo: "git@github.com:EchoXigua/vue3-ts-xg.git"
          destination-repo: "git@1.12.36.97:13822/front-end/vue3-ts-xg.git"
